### PR TITLE
Implement GraphQL / Sqlite server

### PR DESCRIPTION
**Pull request by zackzeyu**
GraphQL and Sqlite are connected and API is served via a single /graphql endpoint

### CODE REVIEW

**Comment by zackzeyu** [comment]
[Booking Component - Create and run unit tests for server](https://trello.com/c/adEU5hLy/20-booking-component-create-and-run-unit-tests-for-server)

**Comment by zackzeyu** [comment]
[Booking Component - Establish sqlite schemas and seed with generated data](https://trello.com/c/SV7eNijN/11-booking-component-establish-sqlite-schemas-and-seed-with-generated-data)

**Comment by zackzeyu** [comment]
[Booking Component - Connect GraphQL with Sqlite database](https://trello.com/c/B3js8x0n/19-booking-component-connect-graphql-with-sqlite-database)

**Comment by zackzeyu** [comment]
[Booking Component - Establish necessary schema for GraphQL](https://trello.com/c/zNyHgupg/18-booking-component-establish-necessary-schema-for-graphql)

**Comment by zackzeyu** [comment]
[Reviews Component - Design a schema and retrieve generated reviews from db](https://trello.com/c/DCKu5neY/13-reviews-component-design-a-schema-and-retrieve-generated-reviews-from-db)

**Comment by zackzeyu** [comment]
[Booking Component - Install GraphQL / Apollo server and start integration with Express](https://trello.com/c/uYVrou9K/17-booking-component-install-graphql-apollo-server-and-start-integration-with-express)

**Comment by ohbrian19** [comment]
Looks Good!

**Review by calicodes23 — APPROVED** [review]
"looks good and ready to merge"

**Comment by zackzeyu** [comment]
[Booking Component - Merge GraphQL branch back to master](https://trello.com/c/ugakIv4N/24-booking-component-merge-graphql-branch-back-to-master)

**Pull request merged**
