### PR TITLE
Implement server tests using Jest/Supertest

### PR DESCRIPTION
**Pull request by zackzeyu**
Please approve!

### CODE REVIEW

**Comment by zackzeyu** [comment]
[Booking Component - Create and run unit tests for server](https://trello.com/c/adEU5hLy/20-booking-component-create-and-run-unit-tests-for-server)

**Comment by ohbrian19** [comment]
Great!

**Comment by zackzeyu** [comment]
[Booking Component - Implement fully connected GraphQL / sqlite server](https://trello.com/c/TQMcvmO5/15-booking-component-implement-fully-connected-graphql-sqlite-server)

**Comment by zackzeyu** [comment]
[Booking Component - Implement fully connected GraphQL / sqlite server](https://trello.com/c/TQMcvmO5/15-booking-component-implement-fully-connected-graphql-sqlite-server)

**Pull request merged**
